### ISSUE TITLE
Unable to get pack-ami to run - No such file or directory: 'packer'

### ISSUE THREAD

**Issue by sjoneill** [segmentio/stack#153]
No sure what the problem is... I've tried pulling down segmentio's sample repo and still having the same trouble.

`[ 14:45:23 ] | ~/repos/stack/tools (master)$ saml2aws exec "./pack-ami build -t base -p ../packer/"
Running command as: arn:aws:sts::*SNIP*
==> base: working directory is /var/folders/0q/74yhr1z96pq07ghbj4bx8z700000gp/T/tmpjes15k_t
==> base: packer build plan.json
Traceback (most recent call last):
  File "./pack-ami", line 470, in <module>
    main(sys.argv[1:])
  File "./pack-ami", line 21, in main
    function(args)
  File "./pack-ami", line 84, in command_build
    t.do('build', templates_dir=os.path.join(os.getcwd(), options.path), recurse=options.recurse)
  File "./pack-ami", line 356, in do
    ami = self.do_self(command, templates_dir=templates_dir, source_ami=source_ami)
  File "./pack-ami", line 385, in do_self
    packer = subprocess.Popen(cmd, stdin=stdin, stdout=stdout, stderr=stderr, cwd=pwd)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'packer'
exit status 1

[ 14:45:51 ] | ~/repos/stack/tools (master)$ ls ../packer
base ecs

[ 14:45:51 ] | ~/repos/stack/tools (master)$`

**Comment by achille-roussel** [comment]
Packer is a tool from HashiCorp that the pack-ami wrapper is based on. It needs to be installed for this to work. 

See https://www.packer.io/intro/index.html

**Comment by sjoneill** [comment]
Thank you !
